/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Comparador de Preços API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ActionBody,
  AdminOferta,
  AdminStats,
  AdminUsuario,
  Alerta,
  AlertaMatchResult,
  CreateAlertaBody,
  CreateOfertaBody,
  CreateUsuarioBody,
  EconomiaDiaria,
  ErrorResponse,
  GetAlertaMatchesParams,
  GetAlertasParams,
  GetHistoricoPrecosParams,
  HealthStatus,
  HistoricoPrecoItem,
  HomeStats,
  ListFavoritosParams,
  ListOfertasParams,
  LoginBody,
  Oferta,
  Perfil,
  RemoveFavoritoParams,
  SaveFavoritoBody,
  SuccessResponse,
  UsuarioCriado,
  UsuarioRanking,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List offers
 */
export const getListOfertasUrl = (params?: ListOfertasParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/ofertas?${stringifiedParams}`
    : `/api/ofertas`;
};

export const listOfertas = async (
  params?: ListOfertasParams,
  options?: RequestInit,
): Promise<Oferta[]> => {
  return customFetch<Oferta[]>(getListOfertasUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListOfertasQueryKey = (params?: ListOfertasParams) => {
  return [`/api/ofertas`, ...(params ? [params] : [])] as const;
};

export const getListOfertasQueryOptions = <
  TData = Awaited<ReturnType<typeof listOfertas>>,
  TError = ErrorType<unknown>,
>(
  params?: ListOfertasParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOfertas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOfertasQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listOfertas>>> = ({
    signal,
  }) => listOfertas(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOfertas>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOfertasQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOfertas>>
>;
export type ListOfertasQueryError = ErrorType<unknown>;

/**
 * @summary List offers
 */

export function useListOfertas<
  TData = Awaited<ReturnType<typeof listOfertas>>,
  TError = ErrorType<unknown>,
>(
  params?: ListOfertasParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOfertas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOfertasQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new offer
 */
export const getCreateOfertaUrl = () => {
  return `/api/ofertas`;
};

export const createOferta = async (
  createOfertaBody: CreateOfertaBody,
  options?: RequestInit,
): Promise<Oferta> => {
  return customFetch<Oferta>(getCreateOfertaUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOfertaBody),
  });
};

export const getCreateOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOferta>>,
    TError,
    { data: BodyType<CreateOfertaBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOferta>>,
  TError,
  { data: BodyType<CreateOfertaBody> },
  TContext
> => {
  const mutationKey = ["createOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOferta>>,
    { data: BodyType<CreateOfertaBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createOferta(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOferta>>
>;
export type CreateOfertaMutationBody = BodyType<CreateOfertaBody>;
export type CreateOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a new offer
 */
export const useCreateOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOferta>>,
    TError,
    { data: BodyType<CreateOfertaBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOferta>>,
  TError,
  { data: BodyType<CreateOfertaBody> },
  TContext
> => {
  return useMutation(getCreateOfertaMutationOptions(options));
};

/**
 * @summary Delete an offer
 */
export const getDeleteOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}`;
};

export const deleteOferta = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteOfertaUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOferta>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOferta>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteOferta(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOferta>>
>;

export type DeleteOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Delete an offer
 */
export const useDeleteOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOferta>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteOfertaMutationOptions(options));
};

/**
 * @summary Like an offer
 */
export const getLikeOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/like`;
};

export const likeOferta = async (
  id: number,
  actionBody: ActionBody,
  options?: RequestInit,
): Promise<Oferta> => {
  return customFetch<Oferta>(getLikeOfertaUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(actionBody),
  });
};

export const getLikeOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof likeOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  const mutationKey = ["likeOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof likeOferta>>,
    { id: number; data: BodyType<ActionBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return likeOferta(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LikeOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof likeOferta>>
>;
export type LikeOfertaMutationBody = BodyType<ActionBody>;
export type LikeOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Like an offer
 */
export const useLikeOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof likeOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof likeOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  return useMutation(getLikeOfertaMutationOptions(options));
};

/**
 * @summary Validate an offer
 */
export const getValidarOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/validar`;
};

export const validarOferta = async (
  id: number,
  actionBody: ActionBody,
  options?: RequestInit,
): Promise<Oferta> => {
  return customFetch<Oferta>(getValidarOfertaUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(actionBody),
  });
};

export const getValidarOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validarOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof validarOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  const mutationKey = ["validarOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof validarOferta>>,
    { id: number; data: BodyType<ActionBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return validarOferta(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ValidarOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof validarOferta>>
>;
export type ValidarOfertaMutationBody = BodyType<ActionBody>;
export type ValidarOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Validate an offer
 */
export const useValidarOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof validarOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof validarOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  return useMutation(getValidarOfertaMutationOptions(options));
};

/**
 * @summary Report a suspicious offer
 */
export const getDenunciarOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/denunciar`;
};

export const denunciarOferta = async (
  id: number,
  actionBody: ActionBody,
  options?: RequestInit,
): Promise<Oferta> => {
  return customFetch<Oferta>(getDenunciarOfertaUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(actionBody),
  });
};

export const getDenunciarOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof denunciarOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof denunciarOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  const mutationKey = ["denunciarOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof denunciarOferta>>,
    { id: number; data: BodyType<ActionBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return denunciarOferta(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DenunciarOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof denunciarOferta>>
>;
export type DenunciarOfertaMutationBody = BodyType<ActionBody>;
export type DenunciarOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Report a suspicious offer
 */
export const useDenunciarOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof denunciarOferta>>,
    TError,
    { id: number; data: BodyType<ActionBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof denunciarOferta>>,
  TError,
  { id: number; data: BodyType<ActionBody> },
  TContext
> => {
  return useMutation(getDenunciarOfertaMutationOptions(options));
};

/**
 * @summary Toggle featured status on an offer
 */
export const getDestacarOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/destacar`;
};

export const destacarOferta = async (
  id: number,
  options?: RequestInit,
): Promise<AdminOferta> => {
  return customFetch<AdminOferta>(getDestacarOfertaUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getDestacarOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof destacarOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof destacarOferta>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["destacarOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof destacarOferta>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return destacarOferta(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DestacarOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof destacarOferta>>
>;

export type DestacarOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Toggle featured status on an offer
 */
export const useDestacarOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof destacarOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof destacarOferta>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDestacarOfertaMutationOptions(options));
};

/**
 * @summary Toggle sponsored status on an offer
 */
export const getPatrocinarOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/patrocinar`;
};

export const patrocinarOferta = async (
  id: number,
  options?: RequestInit,
): Promise<AdminOferta> => {
  return customFetch<AdminOferta>(getPatrocinarOfertaUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getPatrocinarOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patrocinarOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patrocinarOferta>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["patrocinarOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patrocinarOferta>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return patrocinarOferta(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatrocinarOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof patrocinarOferta>>
>;

export type PatrocinarOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Toggle sponsored status on an offer
 */
export const usePatrocinarOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patrocinarOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof patrocinarOferta>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getPatrocinarOfertaMutationOptions(options));
};

/**
 * @summary Reset reports on an offer and mark as valid
 */
export const getResetarDenunciasOfertaUrl = (id: number) => {
  return `/api/ofertas/${id}/resetar-denuncias`;
};

export const resetarDenunciasOferta = async (
  id: number,
  options?: RequestInit,
): Promise<AdminOferta> => {
  return customFetch<AdminOferta>(getResetarDenunciasOfertaUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getResetarDenunciasOfertaMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetarDenunciasOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetarDenunciasOferta>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["resetarDenunciasOferta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetarDenunciasOferta>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return resetarDenunciasOferta(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetarDenunciasOfertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof resetarDenunciasOferta>>
>;

export type ResetarDenunciasOfertaMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Reset reports on an offer and mark as valid
 */
export const useResetarDenunciasOferta = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetarDenunciasOferta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof resetarDenunciasOferta>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getResetarDenunciasOfertaMutationOptions(options));
};

/**
 * @summary Get user ranking by points
 */
export const getGetRankingUrl = () => {
  return `/api/ranking`;
};

export const getRanking = async (
  options?: RequestInit,
): Promise<UsuarioRanking[]> => {
  return customFetch<UsuarioRanking[]>(getGetRankingUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetRankingQueryKey = () => {
  return [`/api/ranking`] as const;
};

export const getGetRankingQueryOptions = <
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRanking>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetRankingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRanking>>> = ({
    signal,
  }) => getRanking({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRanking>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetRankingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRanking>>
>;
export type GetRankingQueryError = ErrorType<unknown>;

/**
 * @summary Get user ranking by points
 */

export function useGetRanking<
  TData = Awaited<ReturnType<typeof getRanking>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getRanking>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetRankingQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get home statistics
 */
export const getGetStatsUrl = () => {
  return `/api/stats`;
};

export const getStats = async (options?: RequestInit): Promise<HomeStats> => {
  return customFetch<HomeStats>(getGetStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetStatsQueryKey = () => {
  return [`/api/stats`] as const;
};

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({
    signal,
  }) => getStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStats>>
>;
export type GetStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get home statistics
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List alerts for a user
 */
export const getGetAlertasUrl = (params: GetAlertasParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/alertas?${stringifiedParams}`
    : `/api/alertas`;
};

export const getAlertas = async (
  params: GetAlertasParams,
  options?: RequestInit,
): Promise<Alerta[]> => {
  return customFetch<Alerta[]>(getGetAlertasUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAlertasQueryKey = (params?: GetAlertasParams) => {
  return [`/api/alertas`, ...(params ? [params] : [])] as const;
};

export const getGetAlertasQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlertas>>,
  TError = ErrorType<unknown>,
>(
  params: GetAlertasParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAlertas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAlertasQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlertas>>> = ({
    signal,
  }) => getAlertas(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAlertas>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAlertasQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlertas>>
>;
export type GetAlertasQueryError = ErrorType<unknown>;

/**
 * @summary List alerts for a user
 */

export function useGetAlertas<
  TData = Awaited<ReturnType<typeof getAlertas>>,
  TError = ErrorType<unknown>,
>(
  params: GetAlertasParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAlertas>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAlertasQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a price alert
 */
export const getCreateAlertaUrl = () => {
  return `/api/alertas`;
};

export const createAlerta = async (
  createAlertaBody: CreateAlertaBody,
  options?: RequestInit,
): Promise<Alerta> => {
  return customFetch<Alerta>(getCreateAlertaUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAlertaBody),
  });
};

export const getCreateAlertaMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAlerta>>,
    TError,
    { data: BodyType<CreateAlertaBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAlerta>>,
  TError,
  { data: BodyType<CreateAlertaBody> },
  TContext
> => {
  const mutationKey = ["createAlerta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAlerta>>,
    { data: BodyType<CreateAlertaBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createAlerta(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAlertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAlerta>>
>;
export type CreateAlertaMutationBody = BodyType<CreateAlertaBody>;
export type CreateAlertaMutationError = ErrorType<unknown>;

/**
 * @summary Create a price alert
 */
export const useCreateAlerta = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAlerta>>,
    TError,
    { data: BodyType<CreateAlertaBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createAlerta>>,
  TError,
  { data: BodyType<CreateAlertaBody> },
  TContext
> => {
  return useMutation(getCreateAlertaMutationOptions(options));
};

/**
 * @summary Count current offers that match user alerts
 */
export const getGetAlertaMatchesUrl = (params: GetAlertaMatchesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/alertas/matches?${stringifiedParams}`
    : `/api/alertas/matches`;
};

export const getAlertaMatches = async (
  params: GetAlertaMatchesParams,
  options?: RequestInit,
): Promise<AlertaMatchResult> => {
  return customFetch<AlertaMatchResult>(getGetAlertaMatchesUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAlertaMatchesQueryKey = (
  params?: GetAlertaMatchesParams,
) => {
  return [`/api/alertas/matches`, ...(params ? [params] : [])] as const;
};

export const getGetAlertaMatchesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAlertaMatches>>,
  TError = ErrorType<unknown>,
>(
  params: GetAlertaMatchesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAlertaMatches>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAlertaMatchesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAlertaMatches>>
  > = ({ signal }) => getAlertaMatches(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAlertaMatches>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAlertaMatchesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAlertaMatches>>
>;
export type GetAlertaMatchesQueryError = ErrorType<unknown>;

/**
 * @summary Count current offers that match user alerts
 */

export function useGetAlertaMatches<
  TData = Awaited<ReturnType<typeof getAlertaMatches>>,
  TError = ErrorType<unknown>,
>(
  params: GetAlertaMatchesParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getAlertaMatches>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAlertaMatchesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a price alert
 */
export const getDeleteAlertaUrl = (id: number) => {
  return `/api/alertas/${id}`;
};

export const deleteAlerta = async (
  id: number,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getDeleteAlertaUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAlertaMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAlerta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAlerta>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteAlerta"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAlerta>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteAlerta(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAlertaMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAlerta>>
>;

export type DeleteAlertaMutationError = ErrorType<unknown>;

/**
 * @summary Delete a price alert
 */
export const useDeleteAlerta = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAlerta>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteAlerta>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteAlertaMutationOptions(options));
};

/**
 * @summary Create a new user account
 */
export const getCreateUsuarioUrl = () => {
  return `/api/usuarios`;
};

export const createUsuario = async (
  createUsuarioBody: CreateUsuarioBody,
  options?: RequestInit,
): Promise<UsuarioCriado> => {
  return customFetch<UsuarioCriado>(getCreateUsuarioUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUsuarioBody),
  });
};

export const getCreateUsuarioMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUsuario>>,
    TError,
    { data: BodyType<CreateUsuarioBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUsuario>>,
  TError,
  { data: BodyType<CreateUsuarioBody> },
  TContext
> => {
  const mutationKey = ["createUsuario"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUsuario>>,
    { data: BodyType<CreateUsuarioBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createUsuario(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUsuario>>
>;
export type CreateUsuarioMutationBody = BodyType<CreateUsuarioBody>;
export type CreateUsuarioMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create a new user account
 */
export const useCreateUsuario = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUsuario>>,
    TError,
    { data: BodyType<CreateUsuarioBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createUsuario>>,
  TError,
  { data: BodyType<CreateUsuarioBody> },
  TContext
> => {
  return useMutation(getCreateUsuarioMutationOptions(options));
};

/**
 * @summary Login with CPF and telefone
 */
export const getLoginUsuarioUrl = () => {
  return `/api/usuarios/login`;
};

export const loginUsuario = async (
  loginBody: LoginBody,
  options?: RequestInit,
): Promise<UsuarioCriado> => {
  return customFetch<UsuarioCriado>(getLoginUsuarioUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginBody),
  });
};

export const getLoginUsuarioMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUsuario>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUsuario>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  const mutationKey = ["loginUsuario"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUsuario>>,
    { data: BodyType<LoginBody> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUsuario(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUsuario>>
>;
export type LoginUsuarioMutationBody = BodyType<LoginBody>;
export type LoginUsuarioMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Login with CPF and telefone
 */
export const useLoginUsuario = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUsuario>>,
    TError,
    { data: BodyType<LoginBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUsuario>>,
  TError,
  { data: BodyType<LoginBody> },
  TContext
> => {
  return useMutation(getLoginUsuarioMutationOptions(options));
};

/**
 * @summary Get user profile
 */
export const getGetPerfilUrl = (id: number) => {
  return `/api/perfil/${id}`;
};

export const getPerfil = async (
  id: number,
  options?: RequestInit,
): Promise<Perfil> => {
  return customFetch<Perfil>(getGetPerfilUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetPerfilQueryKey = (id: number) => {
  return [`/api/perfil/${id}`] as const;
};

export const getGetPerfilQueryOptions = <
  TData = Awaited<ReturnType<typeof getPerfil>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPerfil>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPerfilQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPerfil>>> = ({
    signal,
  }) => getPerfil(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getPerfil>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetPerfilQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPerfil>>
>;
export type GetPerfilQueryError = ErrorType<ErrorResponse>;

/**
 * @summary Get user profile
 */

export function useGetPerfil<
  TData = Awaited<ReturnType<typeof getPerfil>>,
  TError = ErrorType<ErrorResponse>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getPerfil>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPerfilQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get admin statistics
 */
export const getGetAdminStatsUrl = () => {
  return `/api/admin/stats`;
};

export const getAdminStats = async (
  options?: RequestInit,
): Promise<AdminStats> => {
  return customFetch<AdminStats>(getGetAdminStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminStatsQueryKey = () => {
  return [`/api/admin/stats`] as const;
};

export const getGetAdminStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({
    signal,
  }) => getAdminStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminStats>>
>;
export type GetAdminStatsQueryError = ErrorType<unknown>;

/**
 * @summary Get admin statistics
 */

export function useGetAdminStats<
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all offers for admin
 */
export const getGetAdminOfertasUrl = () => {
  return `/api/admin/ofertas`;
};

export const getAdminOfertas = async (
  options?: RequestInit,
): Promise<AdminOferta[]> => {
  return customFetch<AdminOferta[]>(getGetAdminOfertasUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminOfertasQueryKey = () => {
  return [`/api/admin/ofertas`] as const;
};

export const getGetAdminOfertasQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminOfertas>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminOfertas>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminOfertasQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminOfertas>>> = ({
    signal,
  }) => getAdminOfertas({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminOfertas>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminOfertasQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminOfertas>>
>;
export type GetAdminOfertasQueryError = ErrorType<unknown>;

/**
 * @summary Get all offers for admin
 */

export function useGetAdminOfertas<
  TData = Awaited<ReturnType<typeof getAdminOfertas>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminOfertas>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminOfertasQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all users for admin
 */
export const getGetAdminUsuariosUrl = () => {
  return `/api/admin/usuarios`;
};

export const getAdminUsuarios = async (
  options?: RequestInit,
): Promise<AdminUsuario[]> => {
  return customFetch<AdminUsuario[]>(getGetAdminUsuariosUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminUsuariosQueryKey = () => {
  return [`/api/admin/usuarios`] as const;
};

export const getGetAdminUsuariosQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminUsuarios>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminUsuarios>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminUsuariosQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminUsuarios>>
  > = ({ signal }) => getAdminUsuarios({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminUsuarios>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminUsuariosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminUsuarios>>
>;
export type GetAdminUsuariosQueryError = ErrorType<unknown>;

/**
 * @summary Get all users for admin
 */

export function useGetAdminUsuarios<
  TData = Awaited<ReturnType<typeof getAdminUsuarios>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminUsuarios>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminUsuariosQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get price history for a product
 */
export const getGetHistoricoPrecosUrl = (params: GetHistoricoPrecosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/historico?${stringifiedParams}`
    : `/api/historico`;
};

export const getHistoricoPrecos = async (
  params: GetHistoricoPrecosParams,
  options?: RequestInit,
): Promise<HistoricoPrecoItem[]> => {
  return customFetch<HistoricoPrecoItem[]>(getGetHistoricoPrecosUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetHistoricoPrecosQueryKey = (
  params?: GetHistoricoPrecosParams,
) => {
  return [`/api/historico`, ...(params ? [params] : [])] as const;
};

export const getGetHistoricoPrecosQueryOptions = <
  TData = Awaited<ReturnType<typeof getHistoricoPrecos>>,
  TError = ErrorType<unknown>,
>(
  params: GetHistoricoPrecosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistoricoPrecos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetHistoricoPrecosQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getHistoricoPrecos>>
  > = ({ signal }) => getHistoricoPrecos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getHistoricoPrecos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHistoricoPrecosQueryResult = NonNullable<
  Awaited<ReturnType<typeof getHistoricoPrecos>>
>;
export type GetHistoricoPrecosQueryError = ErrorType<unknown>;

/**
 * @summary Get price history for a product
 */

export function useGetHistoricoPrecos<
  TData = Awaited<ReturnType<typeof getHistoricoPrecos>>,
  TError = ErrorType<unknown>,
>(
  params: GetHistoricoPrecosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getHistoricoPrecos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetHistoricoPrecosQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get daily economy statistics
 */
export const getGetEconomiaDiariaUrl = () => {
  return `/api/economia`;
};

export const getEconomiaDiaria = async (
  options?: RequestInit,
): Promise<EconomiaDiaria> => {
  return customFetch<EconomiaDiaria>(getGetEconomiaDiariaUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetEconomiaDiariaQueryKey = () => {
  return [`/api/economia`] as const;
};

export const getGetEconomiaDiariaQueryOptions = <
  TData = Awaited<ReturnType<typeof getEconomiaDiaria>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getEconomiaDiaria>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEconomiaDiariaQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getEconomiaDiaria>>
  > = ({ signal }) => getEconomiaDiaria({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getEconomiaDiaria>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetEconomiaDiariaQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEconomiaDiaria>>
>;
export type GetEconomiaDiariaQueryError = ErrorType<unknown>;

/**
 * @summary Get daily economy statistics
 */

export function useGetEconomiaDiaria<
  TData = Awaited<ReturnType<typeof getEconomiaDiaria>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getEconomiaDiaria>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetEconomiaDiariaQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List saved offers for a user
 */
export const getListFavoritosUrl = (params: ListFavoritosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/favoritos?${stringifiedParams}`
    : `/api/favoritos`;
};

export const listFavoritos = async (
  params: ListFavoritosParams,
  options?: RequestInit,
): Promise<number[]> => {
  return customFetch<number[]>(getListFavoritosUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListFavoritosQueryKey = (params?: ListFavoritosParams) => {
  return [`/api/favoritos`, ...(params ? [params] : [])] as const;
};

export const getListFavoritosQueryOptions = <
  TData = Awaited<ReturnType<typeof listFavoritos>>,
  TError = ErrorType<unknown>,
>(
  params: ListFavoritosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFavoritos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListFavoritosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listFavoritos>>> = ({
    signal,
  }) => listFavoritos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFavoritos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListFavoritosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFavoritos>>
>;
export type ListFavoritosQueryError = ErrorType<unknown>;

/**
 * @summary List saved offers for a user
 */

export function useListFavoritos<
  TData = Awaited<ReturnType<typeof listFavoritos>>,
  TError = ErrorType<unknown>,
>(
  params: ListFavoritosParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listFavoritos>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListFavoritosQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Save an offer to favorites
 */
export const getSaveFavoritoUrl = () => {
  return `/api/favoritos`;
};

export const saveFavorito = async (
  saveFavoritoBody: SaveFavoritoBody,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getSaveFavoritoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(saveFavoritoBody),
  });
};

export const getSaveFavoritoMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveFavorito>>,
    TError,
    { data: BodyType<SaveFavoritoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveFavorito>>,
  TError,
  { data: BodyType<SaveFavoritoBody> },
  TContext
> => {
  const mutationKey = ["saveFavorito"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveFavorito>>,
    { data: BodyType<SaveFavoritoBody> }
  > = (props) => {
    const { data } = props ?? {};

    return saveFavorito(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveFavoritoMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveFavorito>>
>;
export type SaveFavoritoMutationBody = BodyType<SaveFavoritoBody>;
export type SaveFavoritoMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Save an offer to favorites
 */
export const useSaveFavorito = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveFavorito>>,
    TError,
    { data: BodyType<SaveFavoritoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof saveFavorito>>,
  TError,
  { data: BodyType<SaveFavoritoBody> },
  TContext
> => {
  return useMutation(getSaveFavoritoMutationOptions(options));
};

/**
 * @summary Remove an offer from favorites
 */
export const getRemoveFavoritoUrl = (
  ofertaId: number,
  params: RemoveFavoritoParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/favoritos/${ofertaId}?${stringifiedParams}`
    : `/api/favoritos/${ofertaId}`;
};

export const removeFavorito = async (
  ofertaId: number,
  params: RemoveFavoritoParams,
  options?: RequestInit,
): Promise<SuccessResponse> => {
  return customFetch<SuccessResponse>(getRemoveFavoritoUrl(ofertaId, params), {
    ...options,
    method: "DELETE",
  });
};

export const getRemoveFavoritoMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorito>>,
    TError,
    { ofertaId: number; params: RemoveFavoritoParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof removeFavorito>>,
  TError,
  { ofertaId: number; params: RemoveFavoritoParams },
  TContext
> => {
  const mutationKey = ["removeFavorito"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof removeFavorito>>,
    { ofertaId: number; params: RemoveFavoritoParams }
  > = (props) => {
    const { ofertaId, params } = props ?? {};

    return removeFavorito(ofertaId, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RemoveFavoritoMutationResult = NonNullable<
  Awaited<ReturnType<typeof removeFavorito>>
>;

export type RemoveFavoritoMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Remove an offer from favorites
 */
export const useRemoveFavorito = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof removeFavorito>>,
    TError,
    { ofertaId: number; params: RemoveFavoritoParams },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof removeFavorito>>,
  TError,
  { ofertaId: number; params: RemoveFavoritoParams },
  TContext
> => {
  return useMutation(getRemoveFavoritoMutationOptions(options));
};

/**
 * @summary Toggle block status on a user
 */
export const getBloquearUsuarioUrl = (id: number) => {
  return `/api/admin/usuarios/${id}/bloquear`;
};

export const bloquearUsuario = async (
  id: number,
  options?: RequestInit,
): Promise<AdminUsuario> => {
  return customFetch<AdminUsuario>(getBloquearUsuarioUrl(id), {
    ...options,
    method: "POST",
  });
};

export const getBloquearUsuarioMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bloquearUsuario>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof bloquearUsuario>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["bloquearUsuario"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof bloquearUsuario>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return bloquearUsuario(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BloquearUsuarioMutationResult = NonNullable<
  Awaited<ReturnType<typeof bloquearUsuario>>
>;

export type BloquearUsuarioMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Toggle block status on a user
 */
export const useBloquearUsuario = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof bloquearUsuario>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof bloquearUsuario>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getBloquearUsuarioMutationOptions(options));
};
