import { Router, type IRouter } from "express";
import healthRouter from "./health";
import ofertasRouter from "./ofertas";
import rankingRouter from "./ranking";
import adminRouter from "./admin";
import usuariosRouter from "./usuarios";
import alertasRouter from "./alertas";
import historicoRouter from "./historico";
import favoritosRouter from "./favoritos";
import followsRouter from "./follows";
import insightsRouter from "./insights";
import mercadosRouter from "./mercados";
import ocrRouter from "./ocr";
import pushRouter from "./push";
import recompensasRouter from "./recompensas";
import adminRecompensasRouter from "./admin-recompensas";
import adminProdutosRouter from "./admin-produtos";
import ofertasUserRouter from "./ofertas-user";
import comentariosRouter from "./comentarios";
import notificacoesRouter from "./notificacoes";
import listaRouter from "./lista";
import internalProductsRouter from "./internal-products";
import adminImageUploadRouter from "./admin-image-upload";
import adminCatalogRouter from "./admin-catalog";
import listaAnaliseRouter from "./lista-analise";
import aiRouter from "./ai";
import growthRouter from "./growth";
import adminOfertaBotRouter from "./admin-ofertabot";

const router: IRouter = Router();

router.use(healthRouter);
router.use(adminRecompensasRouter);
router.use(adminProdutosRouter);
router.use(adminRouter);
router.use(ofertasUserRouter);
router.use(ofertasRouter);
router.use(rankingRouter);
router.use(usuariosRouter);
router.use(alertasRouter);
router.use(historicoRouter);
router.use(favoritosRouter);
router.use(followsRouter);
router.use(insightsRouter);
router.use(mercadosRouter);
router.use(ocrRouter);
router.use(pushRouter);
router.use(recompensasRouter);
router.use(comentariosRouter);
router.use(notificacoesRouter);
router.use(listaRouter);
router.use(listaAnaliseRouter);
router.use(aiRouter);
router.use(growthRouter);
router.use(internalProductsRouter);
router.use(adminImageUploadRouter);
router.use(adminCatalogRouter);
router.use(adminOfertaBotRouter);

export default router;
