-- Migration: Multi-Source Image Catalog Foundation
-- Sprint 4.2.2 — AíCompensa
-- Adds image_source, image_status, selected_by to off_product_images.
-- Safe to run multiple times (all DDL uses IF NOT EXISTS / COALESCE logic).

-- ── 1. image_source: where the image came from ────────────────────────────────
-- OFF      = Open Food Facts community
-- USER     = user upload via the app
-- ADMIN    = manually added/approved by an AíCompensa admin
-- AI       = selected or generated by the AI pipeline
-- BRAND    = provided directly by the product brand
-- CATALOG  = official product catalog / partner feed

ALTER TABLE off_product_images
  ADD COLUMN IF NOT EXISTS image_source TEXT NOT NULL DEFAULT 'OFF'
    CHECK (image_source IN ('OFF', 'USER', 'ADMIN', 'AI', 'BRAND', 'CATALOG'));

-- Back-fill existing rows from the legacy source column
UPDATE off_product_images
   SET image_source = 'USER'
 WHERE source = 'user_upload'
   AND image_source = 'OFF';

-- ── 2. image_status: coarse lifecycle state ───────────────────────────────────
-- candidate = in the candidate pool, not yet selected
-- selected  = chosen as the active image for the product
-- rejected  = explicitly rejected (blurry, wrong product, etc.)
-- review    = needs human or AI review before promotion

ALTER TABLE off_product_images
  ADD COLUMN IF NOT EXISTS image_status TEXT NOT NULL DEFAULT 'candidate'
    CHECK (image_status IN ('candidate', 'selected', 'rejected', 'review'));

-- Map existing status values to the new lifecycle field
UPDATE off_product_images
   SET image_status = CASE
     WHEN status IN ('approved', 'auto_approved') THEN 'selected'
     WHEN status = 'rejected'                     THEN 'rejected'
     ELSE 'candidate'
   END;

-- ── 3. selected_by: how the image was chosen ──────────────────────────────────
-- RULE       = deterministic rule scoring won with sufficient score + delta
-- RULE_PHASH = same as RULE but pHash deduplication was used first
-- AI         = AI visual analysis made the selection
-- ADMIN      = human admin made the selection
-- NONE       = no image was selected

ALTER TABLE off_product_images
  ADD COLUMN IF NOT EXISTS selected_by TEXT
    CHECK (selected_by IN ('RULE', 'RULE_PHASH', 'AI', 'ADMIN', 'NONE'));

-- ── 4. Indexes ────────────────────────────────────────────────────────────────

-- Fast lookup for catalog priority rule (ADMIN/CATALOG official images)
CREATE INDEX IF NOT EXISTS off_images_official
  ON off_product_images (barcode)
  WHERE image_source IN ('ADMIN', 'CATALOG')
    AND image_status = 'selected';

-- Status report queries
CREATE INDEX IF NOT EXISTS off_images_source_status
  ON off_product_images (image_source, image_status);
