-- Migration: disable_ai_product_images
-- Purpose: Remove all AI-generated generic product images from public display.
-- Images generated by gerarImagemPremiumProduto (Gemini 2.5 Flash) are
-- identified by prompt_imagem IS NOT NULL in the produtos table.
-- Off-product images with image_source = 'AI' are rejected.
-- No rows are deleted — admin can still review via status field.

BEGIN;

-- ── Audit counts (informational) ─────────────────────────────────────────────
DO $$
DECLARE
  n_produtos   INTEGER;
  n_off        INTEGER;
BEGIN
  SELECT COUNT(*) INTO n_produtos
    FROM produtos WHERE prompt_imagem IS NOT NULL;
  SELECT COUNT(*) INTO n_off
    FROM off_product_images WHERE image_source = 'AI';
  RAISE NOTICE 'disable_ai_product_images: % produto(s) afetados, % off_product_image(s) afetados',
    n_produtos, n_off;
END $$;

-- ── 1. produtos: null out URL, mark as disabled ───────────────────────────────
-- Identification: prompt_imagem IS NOT NULL (only set by gerarImagemPremiumProduto)
-- Preserves: prompt_imagem (admin can review what was generated)
-- Safe fallback: public feed uses produto_imagens.aprovada=true or fotoUrl
UPDATE produtos
SET
  imagem_premium_url = NULL,
  status_imagem      = 'desativado',
  atualizado_em      = NOW()
WHERE prompt_imagem IS NOT NULL;

-- ── 2. off_product_images: reject AI-sourced images ──────────────────────────
UPDATE off_product_images
SET
  image_status  = 'rejected',
  review_notes  = COALESCE(review_notes || ' | ', '') || 'Desativado: imagem gerada por IA',
  updated_at    = NOW()
WHERE image_source = 'AI'
  AND COALESCE(image_status, 'candidate') != 'rejected';

COMMIT;
