export const IMAGE_SCORE_CONFIG = {
  source: {
    off:          12,
    manual:        8,
    user_upload:   5,
    unknown:       0,
  },
  imageType: {
    front:        25,
    packaging:    15,
    ingredients:   5,
    nutrition:     3,
    other:         0,
  },
  language: {
    pt:   10,
    es:    5,
    other: 2,
  },
  resolution: {
    highPx:      800,
    highScore:    20,
    goodPx:      400,
    goodScore:    14,
    okPx:        200,
    okScore:       7,
    lowPenalty:  -10,
  },
  aspectRatio: {
    squareMin:     0.75,
    squareMax:     1.33,
    squareScore:   10,
    portraitMin:   0.5,
    portraitMax:   2.0,
    portraitScore:  6,
    extremePenalty: -5,
  },
  revision: {
    highThreshold:   20,
    highScore:       10,
    mediumThreshold: 10,
    mediumScore:      7,
    lowThreshold:     4,
    lowScore:         5,
    minScore:         2,
  },
  visual: {
    bonuses: {
      whiteBackground: 8,
      packageCentered: 5,
    },
    penalties: {
      placeholder:      -40,
      shelfPhoto:       -30,
      pricetag:         -25,
      blurry:           -25,
      watermark:        -20,
      logoOnly:         -20,
      cropped:          -15,
      multipleProducts: -15,
    },
    blurThreshold: 20,
  },
  thresholds: {
    minUsefulScore:                30,
    autoApproveScore:              75,
    autoApproveDelta:              12,
    minAcceptableScore:            65,
    hashDuplicateDistance:          5,
    hashNearDuplicateDistance:     10,
    hashPossibleVariationDistance: 15,
  },
} as const;
